### ISSUE TITLE
Saving workflow fails because print_pack is called with too many arguments

### ISSUE THREAD

**Issue by dsmits** [NLeSC/scriptcwl#116]
Tests from TestWorkflowGenerator in the `master` branch are failing because `cwltool.main:print_pack` is called in `scriptcwl/workflow.py:690` with too many arguments.

Stacktrace:
```
Traceback (most recent call last):
  File "/home/dsmits/projects/scriptcwl/tests/test_workflow.py", line 153, in test_save_with_inline_tools
    wf.save(wf_filename, mode='inline')
  File "/home/dsmits/projects/scriptcwl/scriptcwl/workflow.py", line 748, in save
    self._pack(fname, encoding)
  File "/home/dsmits/projects/scriptcwl/scriptcwl/workflow.py", line 690, in _pack
    f.write(print_pack(document_loader, processobj, uri, metadata))
TypeError: print_pack() takes 2 positional arguments but 4 were given
````

**Comment by dsmits** [comment]
It seems that this problem is caused due to changes in `cwltool` in later versions.

**Comment by dsmits** [comment]
I'm closing this issue. The code should be made compatible with the latest version of cwltool. See issue #118
